---
title: "Integration_Test_Human_Colon"
output: html_document
date: '2022-11-30'

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(devtools)
load_all()

knitr::opts_chunk$set(fig.width=12, fig.height=8, out.width = '100%') 

```

## R Markdown

This runs the DSPworkflow package to completion using the Human Colon Dataset:

## 1. Study Design:

```{r Study Design, echo=FALSE}
  
  datadir <- "/rstudio-files/ccr-dceg-data/data/Colon_Dataset"
  DCCFiles <- dir(file.path(datadir, "dccs"), pattern = ".dcc$",
                  full.names = TRUE, recursive = TRUE)
  PKCFiles <- "/rstudio-files/ccr-dceg-data/data/Colon_Dataset/pkcs/Hs_R_NGS_WTA_v1.0.pkc"
  SampleAnnotationFile <- dir(file.path(datadir, "annotation"), pattern = ".xlsx$",
                              full.names = TRUE, recursive = TRUE)
  
  DccColName <- "Sample_ID"
  ProtocolColNames <- c("aoi", "roi")
  ExperimentColNames = c("panel")
  AnnotationSheetName = "SegmentProperties"  
  
  sdesign.list <- StudyDesign(dccFiles = DCCFiles, pkcFiles = PKCFiles,
                      phenoDataFile = SampleAnnotationFile,
                      phenoDataSheet = AnnotationSheetName,
                      phenoDataDccColName = DccColName,
                      protocolDataColNames = ProtocolColNames,
                      experimentDataColNames = ExperimentColNames)
  
  #studyDesignHumanColon <- sdesign.list$dsp.obj
  
  #saveRDS(studyDesignHumanColon, file = "studyDesignHumanColon.RDS")
  
  print(sdesign.list$plot)
  print("Created GeoMx Object\n\n")
  pData(sdesign.list$dsp.obj)[,c("slide name","class","segment")]  
  
  
```

## 2. QC Preprocessing:

```{r QC Preprocessing, echo=FALSE}

QCoutput <-  QcProc(object = sdesign.list$dsp.obj,
                        minSegmentReads = 1000, 
                        percentTrimmed = 80,    
                        percentStitched = 80,   
                        percentAligned = 80,    
                        percentSaturation = 50, 
                        minNegativeCount = 10,   
                        maxNTCCount = 1000,     
                        minNuclei = 200,         
                        minArea = 16000)
    print(QCoutput$segments.qc)
    
    #qcHumanColon <- QCoutput$dsp.target
    
    #saveRDS(qcHumanColon, file = "qcHumanColon.RDS")

```

## 3. Filtering:

```{r Filtering, echo=FALSE}
    
    PKFil <- annotation(QCoutput$dsp.target)
    target_demoDataFil <- QCoutput$dsp.target
    demoDataFil <- QCoutput$dsp.target
    
    genes <- c("PDCD1", "CD274", "IFNG", "CD8A", "CD68", "EPCAM", "KRT18", "NPHS1", "NPHS2", "CALB1", "CLDN8")
    
    FiltOutput <- filtering(Data = target_demoDataFil, 
                            dsp_obj = demoDataFil, 
                            PKCS = PKFil, 
                            LOQcutoff = 2, 
                            LOQmin = 2, 
                            CutSegment = .05, 
                            GOI = genes)
    print(FiltOutput$`Stacked Bar Plot`)
    print(FiltOutput$`Table of Cuts`)
    print(FiltOutput$`Sankey Plot`)
    print(FiltOutput$`Genes Deccted Plot`)
    
    #filteringHumanColon <- FiltOutput$`target_demoData Dataset`
    
    #saveRDS(filteringHumanColon, file = "filteringHumanColon.RDS")

```


## 4. Normalization:
  
```{r Normalization, echo=FALSE}
  
    target_demoDataNorm <- FiltOutput$`target_demoData Dataset`
    
    NormOut.list <- GeoMxNorm(target_demoDataNorm, "quant")
  
    #normalizationHumanColon <- NormOut.list$`Normalized Dataframe`
    
    #saveRDS(normalizationHumanColon, file = "normalizationHumanColon.RDS")
    
    print(NormOut.list$plot)
    print(NormOut.list$Boxplot)
    
```


## 5. Unsupervised Analysis:

```{r Unsupervised Analysis, echo=FALSE}

    #Test Unsupervised Analysis:
    target.Data <- NormOut.list$`Normalized Dataframe`
    UnSupervisedoutput <- DimReduct(object = target.Data,
                        point.size = 3,
                        point.alpha = 1,
                        color.variable1 = "region",
                        shape.variable = "class"
    )
    
    #unsupervisedAnalysisHumanColon <- UnSupervisedoutput$dsp.object
    
    #saveRDS(unsupervisedAnalysisHumanColon, file = "unsupervisedAnalysisHumanColon.RDS")
    
    print(UnSupervisedoutput$plot.list$PCA)
    print(UnSupervisedoutput$plot.list$tSNE)
    print(UnSupervisedoutput$plot.list$UMAP)

```


## 6. Clustering high CV Genes and Heatmap:

 
```{r Clustering high CV Genes, echo=FALSE}

    target.Data <- UnSupervisedoutput$dsp.object  
    
    dsp.list <- HeatMap(target.data = target.Data, 
                        ngenes = 200, 
                        image.width = 3600, 
                        image.height = 1800, 
                        image.resolution = 300, 
                        image.filename = "heatmap.clust.highCVgenes.png",
                        scale.by.row.or.col = "row", 
                        show.rownames = FALSE, 
                        show.colnames = FALSE, 
                        clustering.method = "average", 
                        cluster.rows = TRUE, 
                        cluster.cols = TRUE,
                        clustering.distance.rows = "correlation", 
                        clustering.distance.cols = "correlation", 
                        annotation.row = NA, 
                        annotation.col = c("class", "segment", "region"), 
                        breaks.by.values = seq(-3, 3, 0.05), 
                        heatmap.color = colorRampPalette(c("blue", "white", "red"))(120), 
                        norm.method = "quant")


    print(dsp.list$plot)
    
  
```


## 7. Differential Expression Analysis:


```{r Differential Expression Analysis,  echo=FALSE}

    data <- UnSupervisedoutput$dsp.object 
    goi <- c("IGHA1", "JCHAIN", "IGKC", "IGLL5", "PIGR", "CCL8", "CD37", "CXCL13", "MS4A1", "CCL19", "CCL21")
    data <- data[goi,]
    Gene <- Subset <- NULL
    
    #First analysis:
    reslist.1 <- DiffExpr(object = data, 
                          analysisType = "Within Groups", 
                          regionCol = "segment", 
                          regions = c("PanCK+", "PanCK-"), 
                          groupCol = "region", 
                          groups = c("Lamina"), 
                          slideCol = "slide name")
    grid.draw(reslist.1$sample_table)
    grid.newpage()
    grid.draw(reslist.1$summary_table)
    
    lfc_col1 <- colnames(reslist.1$result)[grepl("logFC",colnames(reslist.1$result))]
    pval_col1 <- colnames(reslist.1$result)[grepl("_pval",colnames(reslist.1$result))]
    
    lfc.1 <- reslist.1$result %>% 
              dplyr::filter(Gene == "JCHAIN" & Subset == "Lamina") %>% 
              select(all_of(lfc_col1)) %>% 
              as.numeric()
    pval.1 <- reslist.1$result %>% 
              dplyr::filter(Gene == "JCHAIN" & Subset == "Lamina") %>% 
              select(all_of(pval_col1)) %>% 
              as.numeric()
    
    cat(paste0("\n\nvalue of JCHAIN Fold Change is:", lfc.1))
    cat("expected value is unknown")
    
    cat(paste0("\nvalue of JCHAIN pval is:",pval.1))
    cat("expected value is unknown")
    
    #Second analysis:
    reslist.2 <- DiffExpr(object = data, 
                          analysisType = "Between Groups", 
                          regionCol = "class", 
                          regions = c("colon"), 
                          groupCol = "region", 
                          groups = c("Lymphoid", "Lamina"), 
                          slideCol = "slide name")
    grid.draw(reslist.2$sample_table)
    grid.newpage()
    grid.draw(reslist.2$summary_table)
    
    lfc_col2 <- colnames(reslist.2$result)[grepl("logFC",colnames(reslist.2$result))]
    pval_col2 <- colnames(reslist.2$result)[grepl("_pval",colnames(reslist.2$result))]
    
    lfc.2 <- reslist.2$result %>% 
              dplyr::filter(Gene == "JCHAIN" & Subset == "colon") %>% 
              select(all_of(lfc_col2)) %>% 
              as.numeric()
    pval.2 <- reslist.2$result %>% 
              dplyr::filter(Gene == "JCHAIN" & Subset == "colon") %>% 
              select(all_of(pval_col2)) %>% 
              as.numeric()
    
    cat(paste0("\n\nvalue of JCHAIN Fold Change is:", lfc.2))
    cat("expected value is negative")
    
    cat(paste0("\nvalue of JCHAIN pval is:",pval.2))
    cat("expected value is significant")

```
## 8. Volcano Plot

#This part is run on NIDAP.

## 9. Violin Plot

```{r Violin Plot, echo=FALSE}

    test_data <- UnSupervisedoutput$dsp.object
    
    #test_genes <- head(rownames(test_data@assayData$q_norm),5)
    
    test_genes <- c("JCHAIN")
    
    violin_plot_test <- violin_function(data = test_data, 
                                        genes = test_genes,
                                        group = "region")
    grid.arrange(violin_plot_test)
    
    #print("Violin Plot Done")

```

## 10. Spatial Deconvolution:

```{r Spatial Deconvolution, echo=FALSE}

refdir <- "/rstudio-files/ccr-dceg-data/data/CellProfileLibrary/Human/Adult/"
    load(paste0(refdir,"Kidney_HCA.RData"))
    ref_mtx_test <- profile_matrix
    annot_1 <- data.frame(CellID = colnames(ref_mtx_test),LabeledCellType = colnames(ref_mtx_test))
    
    target_demoData <- UnSupervisedoutput$dsp.object
    dsp_qnorm_test = target_demoData@assayData$q_norm
    dsp_negnorm_test = target_demoData@assayData$q_norm
    
    #To derive neg probes: 
    target_demoData@featureData@data$TargetName[target_demoData@featureData@data$Negative == TRUE] 
    
    dsp_negnorm_test = derive_GeoMx_background(norm = target_demoData@assayData$q_norm,
                                 probepool = fData(target_demoData)$Module,
                                 negnames = c("NegProbe-WTX"))
    
    invisible(capture.output(res <- spatial_deconvolution(dsp_qnorm = dsp_qnorm_test, 
                                                          dsp_negnorm = dsp_negnorm_test, 
                                                          ref_mtx = ref_mtx_test, ref_annot = annot_1)))
    
    # Heatmap of estimated cell fraction ~ res$beta
    print(heatmap(t(res$beta), cexCol = 0.5, cexRow = 0.7, margins = c(10,7)))
    # Heatmap of cell profile matrix used ~ res$X
    print(heatmap(sweep(res$X, 1, apply(res$X, 1, max), "/"), labRow = NA, margins = c(10, 5)))
    # Abundance Barplot - draws legend in a new page 
    print(TIL_barplot(res$prop_of_all, draw_legend = TRUE, cex.names = 0.3))

    print("Spatial Deconvolution Done")

```