name: Adding Files to Merged Main
run-name: ${{ github.actor }} is Adding Files to Merged Main
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  Adding_NAMESPACE_and_man_files:
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/Append_File_On_Merged_to_Main.yml@master
    with:
      image_to_use: ghcr.io/nidap-community/dsp_github_workflow_env:r_env_v1.0