name: Preparing for Merging to main
run-name: ${{ github.actor }} is preparing for merging "${{ github.ref_name }}" to main
on:
  pull_request:
    types:
      - opened
    branches:
      - main 

jobs:
  Integration_Test_and_Check:
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/Check_On_Merge_to_Main.yml@master
    with:
      image_to_use: ghcr.io/nidap-community/dsp_github_workflow_env:r_env_v1.0
