name: Routine Push Check
run-name: ${{ github.actor }} push to "${{ github.ref_name }}" on ${{ github.sha }}
on:
  push:
    branches:
      - '*'
      - '!dev'
      - '!main'
jobs:
  Routine_Check_for_Commit:
    runs-on: ubuntu-latest
    container: ruihe864/dsp_github_workflow_env:R_env_v1.0
    steps:
      - run: echo "Running test in DSPWorkflow container"
      
      - name: Extract branch name
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "Push time: ${{ github.event.head_commit.timestamp }}"
        id: extract_branch

      - uses: actions/checkout@v3
        with:
           token: ${{secrets.GITHUB_TOKEN}}
           ref: ${{ steps.extract_branch.outputs.branch }}
           fetch-depth: 0
           
      - id: Unit Test
        name: Unit test for changed scripts
        run: |
          export current_wd="/__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}"
          echo "$current_wd"
          
          git config --global --add safe.directory "$current_wd"
          
          bash $current_wd/.github/workflows/Check_on_Commit.sh "$current_wd" "${{ github.event.before }}"
        
      - id: Lint Check
        name: Use lintr to check code
        run: |
          export current_wd="/__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}"
          echo "$current_wd"
          
          git config --global --add safe.directory "$current_wd"
          
          bash $current_wd/.github/workflows/Lint_on_Commit.sh "$current_wd" "${{ github.event.before }}"
          
          
      - name: Undo Push
        if: ${{ failure() }}
        run: |
          export current_wd="/__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}"
          echo "$current_wd"
          
          export MY_GIT_TOKEN=${{secrets.GITHUB_TOKEN}}
          export MY_GIT_USERNAME=${{ github.actor }}
          export MY_GIT_EMAIL=${{ github.event.pusher.email }}
          
          git config --global user.name "$MY_GIT_USERNAME"
          git config --global user.email "$MY_GIT_EMAIL"
          git config --global url."https://api:$MY_GIT_TOKEN@github.com/".insteadOf "https://github.com/"
          git config --global url."https://ssh:$MY_GIT_TOKEN@github.com/".insteadOf "ssh://git@github.com/"
          git config --global url."https://git:$MY_GIT_TOKEN@github.com/".insteadOf "git@github.com:"
          
          git clone https://github.com/${GITHUB_REPOSITORY}.git
          
          cd ${GITHUB_REPOSITORY#*/}
          
          git checkout ${{ steps.extract_branch.outputs.branch }}
          
          git reset --hard ${{ github.event.before }}
          
          git push -f origin ${{ steps.extract_branch.outputs.branch }}
