name: Routine Push Check
run-name: ${{ github.actor }} is checking push to "${{ github.ref_name }}"  branch
on:
  push:
    branches:
      - '*'
      - '!dev'
      - '!main'
jobs:
  Routine_Check_for_Commit:
    runs-on: ubuntu-latest
    container: ruihe864/dsp_github_workflow_env:2_13_23
    steps:
      - run: echo "Running test in Official R-base docker container with devtools"
      
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - uses: actions/checkout@v3
        with:
           token: ${{secrets.GITHUB_TOKEN}}
           ref: ${{ steps.extract_branch.outputs.branch }}
           fetch-depth: 0
      
      - id: Build_check
        name: R Build and Checks
        run: |
          export current_wd="/__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}"
          echo "$current_wd"
          
          git config --global --add safe.directory "$current_wd"
          
          bash $current_wd/.github/workflows/Check_on_Commit.sh "$current_wd"
          
          
      - name: Undo Push
        if: ${{ failure() }}
        run: |
          export current_wd="/__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}"
          echo "$current_wd"
          
          export MY_GIT_TOKEN=${{secrets.GITHUB_TOKEN}}
          export MY_GIT_USERNAME=${{ github.actor }}
          export MY_GIT_EMAIL=${{ github.event.pusher.email }}
          
          git config --global user.name "$MY_GIT_USERNAME"
          git config --global user.email "$MY_GIT_EMAIL"
          git config --global url."https://api:$MY_GIT_TOKEN@github.com/".insteadOf "https://github.com/"
          git config --global url."https://ssh:$MY_GIT_TOKEN@github.com/".insteadOf "ssh://git@github.com/"
          git config --global url."https://git:$MY_GIT_TOKEN@github.com/".insteadOf "git@github.com:"
          
          git clone https://github.com/${GITHUB_REPOSITORY}.git
          
          cd ${GITHUB_REPOSITORY#*/}
          
          git checkout ${{ steps.extract_branch.outputs.branch }}
          
          git reset --hard HEAD~1
          
          git commit --amend -m "Undo last push due to error in test()"
          
          git push -f origin ${{ steps.extract_branch.outputs.branch }}
