name: Preparing for Merging to Release
run-name: ${{ github.actor }} is preparing for merging "${{ github.ref_name }}" to Dev
on:
  pull_request:
    types:
      - opened
    branches:
      - release*
jobs:
  Unit_tests:
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/Check_On_Merge_to_Release.yml@master
    with:
      image_to_use: ghcr.io/nidap-community/dsp_github_workflow_env:r_env_v1.0
