name: Gitflow Action for R Package Development
run-name: ${{ github.actor }} ${{ github.event_name }} to ${{ github.ref_name }}

on:
  push:
    branches: ['*', '!dev', '!main', '!release_dev', '!Conda_Package', '!github_page']
    
  pull_request:
    types: ['opened', 'closed']
    branches: ['main', 'release*']

jobs:
  Activating_Parser:
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/parser.yml@master
    with:
      image_to_use: ghcr.io/nidap-community/dsp_ci_cd:latest
      package_name: "r-dspworkflow"
      r_version: "4.1.3"
      artifact_rid_production: "ri.artifacts.main.repository.32a4b1e5-fb24-41a2-a552-fa252206e981"
      artifact_rid_development: "ri.stemma.main.repository.2172e505-c98f-43d4-881a-47e170aadbe1"
    secrets:
      NIDAP_TOKEN_PRODUCTION: ${{ secrets.NIDAP_TOKEN_PRODUCTION }}
      NIDAP_TOKEN_DEVELOPMENT: ${{ secrets.NIDAP_TOKEN_DEVELOPMENT }}
