name: Gitflow Action for R Package Development
run-name: ${{ github.actor }} now ${{ github.event_name }} to ${{ github.ref_name }}

on:
  push:
    branches: ['*', '!dev', '!main']
    
  pull_request:
    types: ['opened', 'closed']
    branches: ['main', 'release*']

jobs:
  Activating_Parser:
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/parser.yml@DSPWorkflow
    with:
      image_to_use: ghcr.io/nidap-community/dsp_github_workflow_env:DSPv0.9.5
      action_branch: DSPWorkflow
